export const actionTypes = {
    ADD_TO_CART: 'ADD_TO_CART',
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    TOGGLE_CART_OPEN: 'TOGGLE_CART_OPEN',
    OPEN_CART :  'OPEN_CART ',
    LOAD_PRODUCTS : 'LOAD_PRODUCTS',
    UPDATE_SORT : 'UPDATE_SORT',
    SORT_PRODUCTS : 'SORT_PRODUCTS',
    UPDATE_FILTERS : 'UPDATE_FILTERS',
    FILTER_PRODUCTS : 'FILTER_PRODUCTS',
    CLEAR_FILTERS : 'CLEAR_FILTERS',
}



